gzip on;
gzip_types
  text/plain
  text/html
  text/xml
  text/css
  text/javascript
  application/json
  application/xml
  application/xhtml+xml
  application/rss+xml
  application/javascript
  application/x-javascript;
gzip_vary on;
#gzip_min_length 1000;
gzip_comp_level 5;
gzip_proxied any;
gzip_buffers 16 8k;