map $scheme $defaultPort {
  http: 80;
  https: 443;
}

# Need to extract port from $http_host, not really available elsewhere
map $http_host $http_port {
  default $defaultPort;
  "~^[^\:]+:(?<p>\d+)$" $p;
}