# Cache most assets for a year
map '' $age {
  default '31536000';
}

map $sent_http_content_type $cache_control_header {
  # ~text/html "public, max-age=600";
  ~image/x-icon "public, max-age=$age";
  ~image/jpeg "public, max-age=$age";
  ~image/jpg "public, max-age=$age";
  ~image/png "public, max-age=$age";
  ~image/gif "public, max-age=$age";
  ~video/mp4 "public, max-age=$age";
  ~text/css "public, max-age=$age";
  ~text/javascript "public, max-age=$age";
  ~application/javascript "public, max-age=$age";
  ~application/x-javascript "public, max-age=$age";
  ~application/xhtml+xml "public, max-age=$age";
}

proxy_hide_header Cache-Control;
add_header Cache-Control $cache_control_header;