# Slowloris protection: Set timeouts if requests come in too slow
client_header_timeout 5s;
client_body_timeout 5s;

# Max request throttling
limit_req_status 500;

# Whitelist own server & services
# Trick: If zone key in limit_req_zone directive is empty string, zone limits are not applied
map $remote_addr $isWhitelisted {
  default 0;
  172.18.0.1 1;       # Docker internal IP
  82.165.122.205 1;   # Own server IP (for frontend SSR)
}

map $isWhitelisted $zoneKey {
  0  $binary_remote_addr$request_uri;
  1  "";
}

limit_req_zone $zoneKey zone=per_url:10m rate=2r/s;

# To activate the rate limiting (can also be placed in lower contexts)
# limit_req zone=per_url burst=5;
