# Allows toggling maintenance mode for individual sites/vhosts. The server config just needs to include this snippet with the following syntax:
#
# set $maintenanceId <unique-id-for-this-server>;
# include conf.d/includes/maintenanceMode.conf;
#
# And then can control maintenance mode via:
# - /maintenance/enable.sh <unique-id-for-this-server>
# - /maintenance/disable.sh <unique-id-for-this-server>

# Configure 503 error page to redirect to maintenance dir
error_page 502 503 504 = @maintenance;

location @maintenance {
  root /maintenance/root;
  try_files $uri /index.html =404;
}

# Trigger 503 is maintenance mode enabled for the page including this file
if (-f /maintenance/enabled/${maintenanceId}) {
  return 503;
}