# If you pass the proxy target as a variable to this include file (or proxy_pass in general), nginx does not do DNS check of target on startup.
# This has the advantage of not erroring if DNS name can't be resolved at the moment. However, it will cause more frequent DNS lookups. 
# It also makes it so "host.docker.internal" can't be resolved - except if you point the DNS resolve to docker's internal DNS IP.

resolver 127.0.0.11 valid=30s;
proxy_pass $proxyTarget;

# Config: Important for some backend services to receive "x-forwarded" headers so they know they are behind a reverse proxy
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Server $http_host;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Port $http_port;




